version: "3.6"
services:

    #/
    #|--------------------------------------------------------------------------
    #| Services
    #|--------------------------------------------------------------------------
    #|
    #|
    #/

    mysql:
      image: mysql:8
      container_name: astrify-mysql
      volumes:
        - ./docker/data/mysql:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=db
        - MYSQL_USER=user
        - MYSQL_ROOT_PASSWORD=password
      ports:
       - "3306:3306"

    redis:
      image: redis:4.0-alpine
      container_name: astrify-redis
      command: redis-server /usr/local/etc/redis/redis.conf
      volumes:
        - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      ports:
        - "6378:6379"
      command: >
        --requirepass secret

    #/
    #|--------------------------------------------------------------------------
    #| Laravel
    #|--------------------------------------------------------------------------
    #|
    #|
    #/

    nginx:
      container_name: astrify-nginx
      image: nginx:alpine
      working_dir: /var/www
      volumes:
         - ./laravel:/var/www
         - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf
      ports:
      - "8000:80"

    # The php api runtime
    laravel:
      container_name: astrify-laravel
      image: benbjurstrom/php-laravel:latest
      environment:
       APP_ENV: container
       APP_MODE: api
       PHP_IDE_CONFIG: serverName=phpfpm
       XDEBUG_CONFIG: idekey=PHPSTORM
      working_dir: /var/www
      volumes:
       - ./laravel:/var/www
