version: '3.7'
services:
    redis:
        image: 'redis:alpine'
        volumes:
            - 'vapor_redis:/data'
        restart: always
    mysql:
        image: 'mysql:5.7'
        volumes:
            - 'vapor_mysql:/var/lib/mysql'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: vapor
            MYSQL_USER: vapor
            MYSQL_PASSWORD: secret
    app:
        image: 'laravelphp/vapor:php73'
        depends_on:
            - mysql
            - redis
        restart: always
        init: true
volumes:
    vapor_mysql: {  }
    vapor_redis: {  }
